import Navbar from '@/components/NavBar'
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='dark' lang="fr">

      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
